# Generated by Django 5.1.6 on 2025-04-29 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('overtime_pay', models.FloatField(blank=True, null=True)),
                ('allowance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=30)),
                ('date_range', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=4)),
                ('pay_cycle', models.IntegerField()),
                ('rate', models.FloatField(blank=True, null=True)),
                ('earning_allowance', models.FloatField(blank=True, null=True)),
                ('deductions_tax', models.FloatField(blank=True, null=True)),
                ('deductions_health', models.FloatField(blank=True, null=True)),
                ('pag_ibig', models.FloatField(blank=True, null=True)),
                ('sss', models.FloatField(blank=True, null=True)),
                ('overtime', models.FloatField(blank=True, null=True)),
                ('total_pay', models.FloatField(blank=True, null=True)),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee')),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
    ]
