# Generated by Django 5.1.6 on 2025-05-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
