# Generated by Django 5.1.6 on 2025-05-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_alter_employee_allowance_alter_employee_overtime_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
