# Generated by Django 5.1.6 on 2025-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_payslip_gross_pay_payslip_total_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ot_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
