# Generated by Django 5.1.6 on 2025-05-12 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_employee_id_alter_employee_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee', to_field='id_number'),
        ),
    ]
