# Generated by Django 5.1.6 on 2025-05-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_alter_payslip_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='id_number',
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee'),
            preserve_default=False,
        ),
    ]
