# Generated by Django 5.1.6 on 2025-05-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_remove_payslip_id_number_payslip_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='employee',
            new_name='id_number',
        ),
    ]
